export {
  DURATION,
  EASING,
  TRANSITION,
  getTransition,
  getSpringConfig as getSpringTransition,
  fadeIn,
  fadeInUp,
  scaleIn,
  slideInLeft,
  slideInRight,
  slideInUp,
  staggerContainer,
  heightCollapse,
  tapScale,
  hoverScale,
  hoverLift,
} from "@/lib/motion"
