import { useState, useCallback, useRef } from "react"
import { motion, AnimatePresence } from "framer-motion"
import {
  GitBranch, GitCommitHorizontal, GitPullRequest, Check, X, Loader2,
  ExternalLink, Copy, Terminal, FileText, Sparkles, AlertCircle,
  Eye, EyeOff, ArrowRight, CheckCircle2,
} from "lucide-react"
import { cn } from "@/lib/utils"
import { useCommitPRStore, type CommitStep } from "@/stores/commit-pr-store"
import { gitCommit, gitPush, gitCheckout, gitBranchList } from "@/lib/git"
import { useWorkspaceStore } from "@/stores/workspace-store"
import { GitHubClient } from "@/lib/github/github-client"
import { useHaptic } from "@/lib/haptics"

const STEP_CONFIG: Record<CommitStep, { label: string; icon: React.ElementType }> = {
  idle: { label: "", icon: GitBranch },
  form: { label: "Commit & PR Details", icon: FileText },
  committing: { label: "Creating commit...", icon: GitCommitHorizontal },
  pushing: { label: "Pushing to remote...", icon: Terminal },
  creating_pr: { label: "Creating pull request...", icon: GitPullRequest },
  done: { label: "Pull request created!", icon: CheckCircle2 },
  error: { label: "Something went wrong", icon: AlertCircle },
}

function sanitizeBranchName(description: string): string {
  return description
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 60) || `feature-${Date.now().toString(36)}`
}

function summarizeChanges(files: { path: string; additions: number; deletions: number }[]): string {
  const parts: string[] = []
  for (const f of files) {
    const name = f.path.split("/").pop() || f.path
    const summary = f.additions > 0 && f.deletions > 0
      ? `${name} (+${f.additions}/-${f.deletions})`
      : f.additions > 0
        ? `${name} (+${f.additions})`
        : f.deletions > 0
          ? `${name} (-${f.deletions})`
          : name
    parts.push(`- ${summary}`)
  }
  return parts.join("\n")
}

function generatePRBody(files: { path: string; additions: number; deletions: number }[]): string {
  const totalAdditions = files.reduce((acc, f) => acc + f.additions, 0)
  const totalDeletions = files.reduce((acc, f) => acc + f.deletions, 0)
  return [
    "## Summary",
    "",
    "Automated changes via AgenticOS.",
    "",
    "## Changes",
    "",
    summarizeChanges(files),
    "",
    totalAdditions > 0 || totalDeletions > 0
      ? `**Stats:** +${totalAdditions} / -${totalDeletions} across ${files.length} file${files.length !== 1 ? "s" : ""}`
      : "",
    "",
    "---",
    "",
    "_Generated by [AgenticOS](https://opencode.ai)_",
  ].filter(Boolean).join("\n")
}

function StepIndicator({ step, currentStep }: { step: CommitStep; currentStep: CommitStep }) {
  const config = STEP_CONFIG[step]
  if (!config) return null
  const isActive = step === currentStep
  const isPast = ["idle", "form", "committing", "pushing", "creating_pr", "done"].indexOf(step) <
    ["idle", "form", "committing", "pushing", "creating_pr", "done"].indexOf(currentStep)

  return (
    <div className="flex items-center gap-2">
      <motion.div
        className={cn(
          "flex items-center justify-center h-6 w-6 rounded-full border transition-all",
          isPast || (isActive && currentStep === "done")
            ? "bg-emerald-500/20 border-emerald-500/40 text-emerald-400"
            : isActive
              ? "bg-blue-500/20 border-blue-500/40 text-blue-400"
              : "bg-white/[0.04] border-white/[0.06] text-white/20",
        )}
        animate={isActive && currentStep !== "done" ? { scale: [1, 1.1, 1] } : {}}
        transition={{ duration: 1.5, repeat: Infinity }}
      >
        {isPast || (isActive && currentStep === "done") ? (
          <Check className="h-3 w-3" />
        ) : isActive && currentStep !== "done" ? (
          <Loader2 className="h-3 w-3 animate-spin" />
        ) : (
          <div className="h-2 w-2 rounded-full bg-white/20" />
        )}
      </motion.div>
      <span className={cn(
        "text-[11px] transition-all",
        isActive ? "text-white/70" : isPast ? "text-white/40" : "text-white/20",
      )}>
        {config.label}
      </span>
    </div>
  )
}

export function CommitPRDialog() {
  const store = useCommitPRStore()
  const rootPath = useWorkspaceStore((s) => s.rootPath)
  const [copied, setCopied] = useState(false)
  const { pulse } = useHaptic()
  const inputRef = useRef<HTMLTextAreaElement>(null)

  const handleClose = useCallback(() => {
    if (store.step === "committing" || store.step === "pushing" || store.step === "creating_pr") return
    store.reset()
  }, [store])

  const handleSubmit = useCallback(async () => {
    if (!rootPath || !store.commitMessage.trim() || !store.branchName.trim()) return
    pulse("medium")

    store.setStep("committing")

    try {
      const branches = await gitBranchList(rootPath)
      const branchExists = branches.includes(store.branchName.trim())

      if (!branchExists) {
        await gitCheckout(rootPath, store.branchName.trim())
      }

      await gitCommit(rootPath, store.commitMessage.trim())
      store.setStep("pushing")
      await gitPush(rootPath, "origin", store.branchName.trim())

      if (!store.owner || !store.repo) {
        store.setError("No GitHub repository configured. Set GITHUB_API_TOKEN and ensure the workspace has a git remote.")
        return
      }

      store.setStep("creating_pr")

      const token = process.env.GITHUB_API_TOKEN || ""
      if (!token) {
        store.setError("No GitHub token configured. Set GITHUB_API_TOKEN environment variable.")
        return
      }

      const client = GitHubClient.getInstance(token)
      const pr = await client.createPullRequest(store.owner, store.repo, {
        title: store.prTitle.trim() || store.commitMessage.trim(),
        head: store.branchName.trim(),
        base: "main",
        body: store.prBody.trim() || generatePRBody(store.filesChanged),
        draft: store.isDraft,
      })

      store.setResult(pr.html_url, pr.number)
      pulse("success")
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      store.setError(msg)
      pulse("error")
    }
  }, [rootPath, store, pulse])

  const handleCopyUrl = useCallback(() => {
    if (store.prUrl) {
      navigator.clipboard.writeText(store.prUrl)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }, [store.prUrl])

  const totalAdditions = store.filesChanged.reduce((acc, f) => acc + f.additions, 0)
  const totalDeletions = store.filesChanged.reduce((acc, f) => acc + f.deletions, 0)

  return (
    <AnimatePresence>
      {store.open && (
        <motion.div
          className="fixed inset-0 z-50 flex items-center justify-center"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.15 }}
        >
          <motion.div
            className="absolute inset-0 bg-black/60 backdrop-blur-sm"
            onClick={handleClose}
          />

          <motion.div
            className="relative w-full max-w-lg mx-4 rounded-xl overflow-hidden border shadow-2xl"
            style={{
              background: "var(--surface-elevated, #141416)",
              borderColor: "var(--border-default, #ffffff12)",
            }}
            initial={{ opacity: 0, scale: 0.95, y: 12 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 12 }}
            transition={{ type: "spring", stiffness: 400, damping: 30 }}
          >
            {/* ── Header ── */}
            <div className="flex items-center gap-3 px-4 py-3 border-b" style={{ borderColor: "var(--border-subtle, #ffffff08)" }}>
              <div className="flex items-center justify-center h-8 w-8 rounded-lg bg-gradient-to-br from-emerald-500/20 to-blue-500/10 border" style={{ borderColor: "var(--border-default, #ffffff12)" }}>
                <GitPullRequest className="h-4 w-4 text-emerald-400" />
              </div>
              <div className="flex-1">
                <h2 className="text-[13px] font-semibold" style={{ color: "var(--text-primary, #e4e4e4)" }}>
                  {store.step === "done" ? "Pull Request Created" : "Commit & Create PR"}
                </h2>
                <p className="text-[10px]" style={{ color: "var(--text-tertiary, #858585)" }}>
                  {store.filesChanged.length} file{store.filesChanged.length !== 1 ? "s" : ""} changed
                  {totalAdditions > 0 && <span className="text-emerald-400 ml-1">+{totalAdditions}</span>}
                  {totalDeletions > 0 && <span className="text-red-400 ml-1">-{totalDeletions}</span>}
                </p>
              </div>
              <button
                onClick={handleClose}
                disabled={store.step === "committing" || store.step === "pushing" || store.step === "creating_pr"}
                className="rounded p-1 transition-colors disabled:opacity-30"
                style={{ color: "var(--text-tertiary, #858585)" }}
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            {/* ── Body ── */}
            <div className="px-4 py-3 space-y-3 max-h-[60vh] overflow-y-auto">
              {/* Step progress (shown during active steps) */}
              {(store.step === "committing" || store.step === "pushing" || store.step === "creating_pr" || store.step === "done") && (
                <div className="space-y-2 py-2">
                  <StepIndicator step="committing" currentStep={store.step} />
                  <StepIndicator step="pushing" currentStep={store.step} />
                  <StepIndicator step="creating_pr" currentStep={store.step} />
                </div>
              )}

              {/* ── Form (shown only in "form" step) ── */}
              {store.step === "form" && (
                <motion.div
                  className="space-y-3"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 0.2 }}
                >
                  {/* Branch name */}
                  <div>
                    <label className="flex items-center gap-1.5 text-[10px] font-medium mb-1.5" style={{ color: "var(--text-secondary, #a0a0a0)" }}>
                      <GitBranch className="h-3 w-3" />
                      Branch name
                    </label>
                    <input
                      value={store.branchName}
                      onChange={(e) => store.setBranchName(e.target.value)}
                      placeholder="feature/my-change"
                      className="w-full rounded-lg px-3 py-2 text-[12px] font-mono outline-none transition-all border"
                      style={{
                        background: "var(--surface-app, #0a0a0b)",
                        color: "var(--text-primary, #e4e4e4)",
                        borderColor: "var(--border-default, #ffffff12)",
                      }}
                    />
                  </div>

                  {/* Commit message */}
                  <div>
                    <label className="flex items-center gap-1.5 text-[10px] font-medium mb-1.5" style={{ color: "var(--text-secondary, #a0a0a0)" }}>
                      <GitCommitHorizontal className="h-3 w-3" />
                      Commit message
                    </label>
                    <textarea
                      ref={inputRef}
                      value={store.commitMessage}
                      onChange={(e) => {
                        store.setCommitMessage(e.target.value)
                        if (!store.prTitle || store.prTitle === store.commitMessage) {
                          store.setPrTitle(e.target.value.split("\n")[0])
                        }
                      }}
                      placeholder="Describe what changed and why"
                      className="w-full rounded-lg px-3 py-2 text-[12px] outline-none resize-none transition-all border"
                      style={{
                        background: "var(--surface-app, #0a0a0b)",
                        color: "var(--text-primary, #e4e4e4)",
                        borderColor: "var(--border-default, #ffffff12)",
                      }}
                      rows={3}
                    />
                  </div>

                  {/* PR Title */}
                  <div>
                    <label className="flex items-center gap-1.5 text-[10px] font-medium mb-1.5" style={{ color: "var(--text-secondary, #a0a0a0)" }}>
                      <GitPullRequest className="h-3 w-3" />
                      PR title
                    </label>
                    <input
                      value={store.prTitle}
                      onChange={(e) => store.setPrTitle(e.target.value)}
                      placeholder="Summary of the changes"
                      className="w-full rounded-lg px-3 py-2 text-[12px] outline-none transition-all border"
                      style={{
                        background: "var(--surface-app, #0a0a0b)",
                        color: "var(--text-primary, #e4e4e4)",
                        borderColor: "var(--border-default, #ffffff12)",
                      }}
                    />
                  </div>

                  {/* PR Description */}
                  <div>
                    <label className="flex items-center gap-1.5 text-[10px] font-medium mb-1.5" style={{ color: "var(--text-secondary, #a0a0a0)" }}>
                      <FileText className="h-3 w-3" />
                      PR description
                    </label>
                    <textarea
                      value={store.prBody}
                      onChange={(e) => store.setPrBody(e.target.value)}
                      placeholder="Detailed description of the changes..."
                      className="w-full rounded-lg px-3 py-2 text-[12px] outline-none resize-none transition-all border"
                      style={{
                        background: "var(--surface-app, #0a0a0b)",
                        color: "var(--text-primary, #e4e4e4)",
                        borderColor: "var(--border-default, #ffffff12)",
                      }}
                      rows={4}
                    />
                  </div>

                  {/* Draft toggle */}
                  <label className="flex items-center gap-2 cursor-pointer">
                    <button
                      onClick={() => store.setIsDraft(!store.isDraft)}
                      className={cn(
                        "flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-[10px] font-medium transition-all border",
                        store.isDraft
                          ? "bg-amber-500/10 border-amber-500/20 text-amber-400"
                          : "bg-white/[0.04] border-white/[0.06] text-white/30",
                      )}
                    >
                      {store.isDraft ? <EyeOff className="h-3 w-3" /> : <Eye className="h-3 w-3" />}
                      {store.isDraft ? "Draft PR" : "Ready for review"}
                    </button>
                    <span className="text-[9px]" style={{ color: "var(--text-quaternary, #606060)" }}>
                      Draft PRs don't request reviews until marked ready
                    </span>
                  </label>

                  {/* Files changed summary */}
                  {store.filesChanged.length > 0 && (
                    <div className="rounded-lg border p-3" style={{ background: "var(--surface-app, #0a0a0b)", borderColor: "var(--border-subtle, #ffffff08)" }}>
                      <span className="text-[10px] font-medium" style={{ color: "var(--text-secondary, #a0a0a0)" }}>Files changed</span>
                      <div className="mt-1.5 space-y-1">
                        {store.filesChanged.map((f) => (
                          <div key={f.path} className="flex items-center gap-2 text-[10px] font-mono">
                            <FileText className="h-2.5 w-2.5 shrink-0" style={{ color: "var(--text-quaternary, #606060)" }} />
                            <span className="truncate flex-1" style={{ color: "var(--text-tertiary, #858585)" }}>
                              {f.path}
                            </span>
                            {f.additions > 0 && <span className="text-emerald-400/60 shrink-0">+{f.additions}</span>}
                            {f.deletions > 0 && <span className="text-red-400/60 shrink-0">-{f.deletions}</span>}
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </motion.div>
              )}

              {/* ── Error state ── */}
              {store.step === "error" && store.error && (
                <motion.div
                  initial={{ opacity: 0, y: -4 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="flex items-start gap-2 rounded-lg border px-3 py-2.5"
                  style={{
                    background: "color-mix(in srgb, #f44747 6%, transparent)",
                    borderColor: "color-mix(in srgb, #f44747 20%, transparent)",
                  }}
                >
                  <AlertCircle className="h-3.5 w-3.5 shrink-0 mt-0.5 text-red-400" />
                  <div className="flex-1 min-w-0">
                    <p className="text-[11px] text-red-300">{store.error}</p>
                    <p className="text-[9px] mt-1" style={{ color: "var(--text-quaternary, #606060)" }}>
                      Check your GitHub token and git configuration, then try again.
                    </p>
                  </div>
                </motion.div>
              )}

              {/* ── Done state ── */}
              {store.step === "done" && store.prUrl && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ type: "spring", stiffness: 300, damping: 25 }}
                  className="flex flex-col items-center py-6 gap-3"
                >
                  <motion.div
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ type: "spring", stiffness: 400, damping: 20, delay: 0.1 }}
                  >
                    <div className="flex items-center justify-center h-14 w-14 rounded-full bg-emerald-500/20 border-2 border-emerald-500/30">
                      <CheckCircle2 className="h-7 w-7 text-emerald-400" />
                    </div>
                  </motion.div>

                  <div className="text-center">
                    <p className="text-[12px] font-semibold" style={{ color: "var(--text-primary, #e4e4e4)" }}>
                      PR #{store.prNumber} created
                    </p>
                    <p className="text-[10px] mt-0.5" style={{ color: "var(--text-tertiary, #858585)" }}>
                      {store.owner}/{store.repo}
                    </p>
                  </div>

                  <div className="flex items-center gap-2">
                    <motion.a
                      href={store.prUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-[11px] font-medium transition-all"
                      style={{
                        background: "var(--color-accent-brand, #0957d0)",
                        color: "var(--text-primary, #e4e4e4)",
                      }}
                      whileHover={{ scale: 1.02 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      <ExternalLink className="h-3 w-3" />
                      Open PR
                    </motion.a>
                    <motion.button
                      onClick={handleCopyUrl}
                      className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-[11px] font-medium transition-all border"
                      style={{
                        color: "var(--text-secondary, #a0a0a0)",
                        borderColor: "var(--border-default, #ffffff12)",
                      }}
                      whileHover={{ scale: 1.02 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      {copied ? (
                        <Check className="h-3 w-3 text-emerald-400" />
                      ) : (
                        <Copy className="h-3 w-3" />
                      )}
                      {copied ? "Copied!" : "Copy URL"}
                    </motion.button>
                  </div>
                </motion.div>
              )}
            </div>

            {/* ── Footer actions ── */}
            {store.step === "form" && (
              <div className="flex items-center justify-end gap-2 px-4 py-3 border-t" style={{ borderColor: "var(--border-subtle, #ffffff08)" }}>
                <button
                  onClick={handleClose}
                  className="rounded-lg px-3 py-1.5 text-[11px] font-medium transition-all"
                  style={{ color: "var(--text-tertiary, #858585)" }}
                >
                  Cancel
                </button>
                <motion.button
                  onClick={handleSubmit}
                  disabled={!store.commitMessage.trim() || !store.branchName.trim()}
                  className="flex items-center gap-1.5 rounded-lg px-4 py-1.5 text-[11px] font-medium transition-all disabled:opacity-40"
                  style={{
                    background: "var(--color-accent-brand, #0957d0)",
                    color: "var(--text-primary, #e4e4e4)",
                  }}
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                >
                  <GitPullRequest className="h-3 w-3" />
                  Create PR
                  <ArrowRight className="h-3 w-3" />
                </motion.button>
              </div>
            )}

            {store.step === "error" && (
              <div className="flex items-center justify-end gap-2 px-4 py-3 border-t" style={{ borderColor: "var(--border-subtle, #ffffff08)" }}>
                <button
                  onClick={() => store.setStep("form")}
                  className="rounded-lg px-3 py-1.5 text-[11px] font-medium transition-all"
                  style={{ color: "var(--text-secondary, #a0a0a0)" }}
                >
                  Back
                </button>
                <motion.button
                  onClick={handleSubmit}
                  className="flex items-center gap-1.5 rounded-lg px-4 py-1.5 text-[11px] font-medium transition-all"
                  style={{ background: "var(--color-accent-brand, #0957d0)", color: "var(--text-primary, #e4e4e4)" }}
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                >
                  <RefreshCwIcon className="h-3 w-3" />
                  Retry
                </motion.button>
              </div>
            )}

            {store.step === "done" && (
              <div className="flex items-center justify-end gap-2 px-4 py-3 border-t" style={{ borderColor: "var(--border-subtle, #ffffff08)" }}>
                <button
                  onClick={store.reset}
                  className="rounded-lg px-3 py-1.5 text-[11px] font-medium transition-all"
                  style={{ color: "var(--text-tertiary, #858585)" }}
                >
                  Close
                </button>
              </div>
            )}
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}

function RefreshCwIcon({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
      <path d="M21 2v6h-6" />
      <path d="M3 12a9 9 0 0 1 15-6.7L21 8" />
      <path d="M3 22v-6h6" />
      <path d="M21 12a9 9 0 0 1-15 6.7L3 16" />
    </svg>
  )
}
