import type { editor } from "monaco-editor"

export const AGENTIC_DARK_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "6A9955", fontStyle: "italic" },
    { token: "keyword", foreground: "569CD6" },
    { token: "keyword.control", foreground: "C586C0" },
    { token: "keyword.operator", foreground: "D4D4D4" },
    { token: "string", foreground: "CE9178" },
    { token: "string.quoted", foreground: "CE9178" },
    { token: "string.key", foreground: "9CDCFE" },
    { token: "number", foreground: "B5CEA8" },
    { token: "type", foreground: "4EC9B0" },
    { token: "type.identifier", foreground: "4EC9B0" },
    { token: "function", foreground: "DCDCAA" },
    { token: "function.declaration", foreground: "DCDCAA" },
    { token: "method", foreground: "DCDCAA" },
    { token: "variable", foreground: "9CDCFE" },
    { token: "variable.instance", foreground: "9CDCFE" },
    { token: "variable.parameter", foreground: "9CDCFE" },
    { token: "constant", foreground: "4FC1FF" },
    { token: "constant.numeric", foreground: "B5CEA8" },
    { token: "regexp", foreground: "D16969" },
    { token: "tag", foreground: "569CD6" },
    { token: "attribute.name", foreground: "9CDCFE" },
    { token: "attribute.value", foreground: "CE9178" },
    { token: "delimiter", foreground: "808080" },
    { token: "metatag", foreground: "DD6B6B" },
    { token: "annotation", foreground: "D7BA7D" },
    { token: "modifier", foreground: "D4D4D4" },
    { token: "identifier", foreground: "D4D4D4" },
    { token: "operator.sql", foreground: "569CD6" },
    { token: "builtin", foreground: "4EC9B0" },
    { token: "namespace", foreground: "4EC9B0" },
    { token: "interface", foreground: "4EC9B0" },
    { token: "enum", foreground: "4EC9B0" },
    { token: "typeParameter", foreground: "4EC9B0" },
    { token: "decorator", foreground: "D7BA7D" },
    { token: "macro", foreground: "C586C0" },
    { token: "label", foreground: "C586C0" },
    { token: "invalid", foreground: "F44747" },
    { token: "invalid.deprecated", foreground: "F44747", fontStyle: "underline" },
  ],
  colors: {
    "editor.background": "#0a0a0b",
    "editor.foreground": "#d4d4d4",
    "editor.lineHighlightBackground": "#ffffff08",
    "editor.selectionBackground": "#264f78",
    "editor.inactiveSelectionBackground": "#3a3d41",
    "editorCursor.foreground": "#569CD6",
    "editorLineNumber.foreground": "#858585",
    "editorLineNumber.activeForeground": "#c6c6c6",
    "editor.selectionHighlightBackground": "#add6ff26",
    "editor.wordHighlightBackground": "#49483E",
    "editor.wordHighlightStrongBackground": "#49483E",
    "editorBracketMatch.background": "#0d3a58",
    "editorBracketMatch.border": "#569cd6",
    "editorGutter.background": "#0c0c0d",
    "editorRuler.foreground": "#ffffff0d",
    "editorWidget.background": "#0c0c0d",
    "editorWidget.border": "#ffffff12",
    "input.background": "#0a0a0b",
    "input.border": "#ffffff12",
    "input.foreground": "#d4d4d4",
    "list.activeSelectionBackground": "#094771",
    "list.hoverBackground": "#2a2d2e",
    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": "#ffffff20",
    "scrollbarSlider.hoverBackground": "#ffffff30",
    "scrollbarSlider.activeBackground": "#ffffff40",
    "minimap.background": "#0a0a0b",
    "minimap.selectionHighlight": "#264f78",
    "minimap.findMatchHighlight": "#d1861660",
    "minimap.errorHighlight": "#f4474740",
    "minimap.warningHighlight": "#cca70040",
    "editorOverviewRuler.background": "#080809",
    "editorOverviewRuler.border": "#ffffff0a",
    "editorOverviewRuler.errorForeground": "#f4474780",
    "editorOverviewRuler.warningForeground": "#cca70080",
    "editorOverviewRuler.infoForeground": "#75beff60",
    "editorOverviewRuler.bracketMatchForeground": "#a0a0a0",
    "editorBracketHighlight.foreground1": "#569CD6",
    "editorBracketHighlight.foreground2": "#CE9178",
    "editorBracketHighlight.foreground3": "#4EC9B0",
    "editorBracketHighlight.foreground4": "#C586C0",
    "editorBracketHighlight.foreground5": "#DCDCAA",
    "editorBracketHighlight.foreground6": "#B5CEA8",
    "editorBracketHighlight.unexpectedBracket.foreground": "#F44747",
    "editorCodeLens.foreground": "#999999",
    "editorError.foreground": "#F44747",
    "editorWarning.foreground": "#CCA700",
    "editorInfo.foreground": "#75BEFF",
    "editorHint.foreground": "#75BEFF",
    "editorUnnecessaryCode.opacity": "#00000077",
    "editorGhostText.foreground": "#ffffff30",
    "editorGhostText.border": "#ffffff10",
    "editorStickyScroll.background": "#0c0c0d",
    "editorStickyScroll.border": "#ffffff0a",
    "breadcrumb.background": "#0c0c0d",
    "breadcrumb.foreground": "#858585",
    "breadcrumb.focusForeground": "#d4d4d4",
    "breadcrumbPicker.background": "#0c0c0d",
    "tab.activeBackground": "#0a0a0b",
    "tab.activeForeground": "#d4d4d4",
    "tab.inactiveBackground": "#0c0c0d",
    "tab.inactiveForeground": "#858585",
    "tab.hoverBackground": "#1a1a1c",
    "tab.border": "#ffffff0a",
    "tab.activeBorderTop": "#569CD6",
    "sideBar.background": "#0c0c0d",
    "sideBar.foreground": "#cccccc",
    "sideBar.border": "#ffffff0a",
    "sideBarTitle.foreground": "#cccccc",
    "sideBarSectionHeader.background": "#0a0a0b",
    "sideBarSectionHeader.foreground": "#cccccc",
    "panel.background": "#0c0c0d",
    "panel.border": "#ffffff0a",
    "panelTitle.activeForeground": "#d4d4d4",
    "panelTitle.inactiveForeground": "#858585",
    "activityBar.background": "#0a0a0b",
    "activityBar.foreground": "#d4d4d4",
    "activityBar.border": "#ffffff0a",
    "activityBarBadge.background": "#569CD6",
    "statusBar.background": "#0a0a0b",
    "statusBar.foreground": "#858585",
    "statusBar.border": "#ffffff0a",
    "titleBar.activeBackground": "#0a0a0b",
    "titleBar.activeForeground": "#cccccc",
    "titleBar.border": "#ffffff0a",
    "notificationCenter.border": "#ffffff12",
    "notificationCenterHeader.background": "#0c0c0d",
    "notifications.background": "#0c0c0d",
    "notifications.border": "#ffffff12",
    "picker.background": "#0c0c0d",
    "picker.border": "#ffffff12",
    "quickInput.background": "#0c0c0d",
    "quickInput.foreground": "#d4d4d4",
    "button.background": "#0957d0",
    "button.foreground": "#ffffff",
    "button.hoverBackground": "#0a6cf1",
    "dropdown.background": "#0c0c0d",
    "dropdown.border": "#ffffff12",
    "dropdown.foreground": "#d4d4d4",
    "checkbox.background": "#0c0c0d",
    "checkbox.border": "#ffffff12",
    "input.placeholderForeground": "#858585",
    "focusBorder": "#569cd6",
    "widget.shadow": "#00000040",
    "progressBar.background": "#569CD6",
    "badge.background": "#094771",
    "badge.foreground": "#d4d4d4",
    "debugExceptionWidget.background": "#0c0c0d",
    "debugExceptionWidget.border": "#ffffff12",
    "debugToolBar.background": "#0c0c0d",
    "diffEditor.insertedTextBackground": "#9bb9551a",
    "diffEditor.removedTextBackground": "#ff00001a",
    "diffEditor.insertedLineBackground": "#9bb9550d",
    "diffEditor.removedLineBackground": "#ff00000d",
    "diffEditor.diagonalFill": "#ffffff12",
    "diffEditorOverview.insertedForeground": "#9bb95580",
    "diffEditorOverview.removedForeground": "#ff000080",
    "merge.currentHeaderBackground": "#9bb95520",
    "merge.incomingHeaderBackground": "#75beff20",
    "merge.commonContentBackground": "#60606020",
    "merge.commonHeaderBackground": "#60606040",
    "editorSuggestWidget.background": "#0c0c0d",
    "editorSuggestWidget.border": "#ffffff12",
    "editorSuggestWidget.foreground": "#d4d4d4",
    "editorSuggestWidget.selectedBackground": "#094771",
    "editorSuggestWidget.highlightForeground": "#569CD6",
    "editorHoverWidget.background": "#0c0c0d",
    "editorHoverWidget.border": "#ffffff12",
    "editorHoverWidget.foreground": "#d4d4d4",
    "editorMarkerNavigation.background": "#0c0c0d",
    "editorMarkerNavigationError.background": "#F44747",
    "editorMarkerNavigationWarning.background": "#CCA700",
    "editorLink.activeForeground": "#569CD6",
    "selection.background": "#264f78",
    "icon.foreground": "#858585",
    "sash.hoverBorder": "#569CD6",
    "commandCenter.background": "#0c0c0d",
    "commandCenter.foreground": "#d4d4d4",
    "commandCenter.activeForeground": "#569CD6",
    "commandCenter.border": "#ffffff12",
    "terminal.background": "#0a0a0b",
    "terminal.foreground": "#e0e0e0",
    "terminal.ansiBlack": "#1e1e1e",
    "terminal.ansiRed": "#cd3131",
    "terminal.ansiGreen": "#0dbc79",
    "terminal.ansiYellow": "#e5e510",
    "terminal.ansiBlue": "#2472c8",
    "terminal.ansiMagenta": "#bc3fbc",
    "terminal.ansiCyan": "#11a8cd",
    "terminal.ansiWhite": "#e5e5e5",
    "terminal.ansiBrightBlack": "#666666",
    "terminal.ansiBrightRed": "#f14c4c",
    "terminal.ansiBrightGreen": "#23d18b",
    "terminal.ansiBrightYellow": "#f5f543",
    "terminal.ansiBrightBlue": "#3b8eea",
    "terminal.ansiBrightMagenta": "#d670d6",
    "terminal.ansiBrightCyan": "#29b8db",
    "terminal.ansiBrightWhite": "#e5e5e5",
    "terminal.selectionBackground": "#264f78",
    "terminalCursor.foreground": "#4ade80",
    "terminalCursor.background": "#0a0a0b",
  },
}
