import type { SkillDefinition } from '../SkillRegistry'

export const prReviewSkill: SkillDefinition = {
  name: 'pr-review',
  description: 'Review a GitHub pull request with detailed inline feedback on correctness, edge cases, style, and test coverage.',
  prompt: [
    'You are reviewing a GitHub pull request as a senior engineer. Be thorough, specific, and constructive.',
    '',
    'Structure your review as follows:',
    '',
    '## Overview',
    '- What does this PR do? (1-2 sentences)',
    '- Is the approach sound?',
    '',
    '## File-by-File Review',
    'For each file changed:',
    '- **Correctness**: Logic errors? Race conditions? Undefined behavior?',
    '- **Edge Cases**: What happens with null/empty/zero inputs? Boundary values?',
    '- **Error Handling**: Are errors caught? Do failures degrade gracefully?',
    '- **Security**: Injection risks? Data exposure? Missing validation?',
    '- **Performance**: Unnecessary allocations? N+1 queries? Blocking I/O in hot path?',
    '- **Style & Conventions**: Does it match the project conventions?',
    '',
    '## Test Coverage',
    '- Are there tests for the new code?',
    '- Do they cover the happy path, error cases, and edge cases?',
    '',
    '## Summary',
    '- **Verdict**: Approve / Request Changes / Needs Discussion',
    '- **Top 3 things to fix** (if any), with specific file:line references',
    '- **What went well** (keep it brief — 1-2 items max)',
    '',
    'Be specific. Reference exact file names and line numbers. Never say "looks good" without justification. Do not add praise for basic correctness.',
  ].join('\n'),
  source: 'bundled',
  tags: ['code-review', 'github', 'pr-review'],
  aliases: ['review-pr', 'pr', 'pull-request-review'],
  requiresConfirmation: false,
}
